name: Build and upload package

on: push

jobs:

  build:

    runs-on: ubuntu-latest
    
    permissions: write-all
    
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}
    
    env:
      TERCEN_SERVICE_URI: ${{ secrets.TERCEN_SERVICE_URI }}
      TERCEN_GITHUB_USER_USERNAME: ${{ secrets.TERCEN_GITHUB_USER_USERNAME }}
      TERCEN_GITHUB_USER_PASSWORD: ${{ secrets.TERCEN_GITHUB_USER_PASSWORD }}
      TERCEN_OPERATOR_STATS_TEAM: ${{ secrets.TERCEN_CRAN_TEAM }}
      TERCEN_OPERATOR_STATS_PROJECT: ${{ secrets.TERCEN_CRAN_PROJECT }}
      GITHUB_REF_NAME: $GITHUB_REF_NAME
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - uses: r-lib/actions/setup-r@v2-branch
      with:
        r-version: ${{ matrix.config.r }}
        http-user-agent: ${{ matrix.config.http-user-agent }}
        
    - name: Build and upload package script
      run: |
        install.packages('pkgbuild')
        source("./examples/build-and-upload.R")
      shell: Rscript {0}